config/routes.rb
Rails.application.routes.draw do
  devise_for :member, path_names: { sign_in: 'login' }

  root 'apartments#index'

  get "apartments/:id", to: "apartments#show", as: :apartment
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  validates :name, presence: true
  has_many_attached :photos, dependent: :destroy

  def cover_photo
    photos[2]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  def index
    @apartments = Apartment.all
  end

  def show
    @apartment = Apartment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/index.html.erb
<div class="container">
  <div class="row row-index">
    <div class="col-8">
      <div class="row text-center">
        <p><%= Apartment.count %> Furnished apartments for rent in <strong>São Paulo</strong></p>
      </div>
      <div class='row'>
        <% @apartments.each do |apartment| %>
          <div class="col-sm-6">
            <%= link_to apartment_path(apartment) do %>
              <div class="card mb-3 card-index">
                <%= image_tag apartment.cover_photo %>
                <div class="card-body">
                  <h5 class="card-title"><%= apartment.neighborhood %></h5>
                  <h3 class="card-subtitle text-truncate"><%= apartment.address %></h3>
                  <p class="card-text"><%= apartment.number_of_bedrooms %> bedroom(s)<strong> . </strong><%= apartment.number_of_bedrooms %> bathroom(s)
                  <h3 class="card-text">from <i class="fa-solid fa-brazilian-real-sign"></i><%= apartment.price_per_month %><small class='text-muted'>/mo</small></h3>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-4">
        <div class="right-image-index">
          <%= image_tag "map", alt: "Static Map", height: 1000 %>
        </div>
    </div>
  </div>
</div>

app/views/apartments/show.html.erb
<div class='top-background-image-show' style="background-image: url(<%= rails_blob_url(@apartment.cover_photo) %>);">
  <div class="default-card header-show">
    <h3><%= @apartment.neighborhood %></h3>
    <h2><%= @apartment.name %> <%= @apartment.address %></h2>
    <h6>
      <span><i class="fa-solid fa-bed"></i><%= @apartment.number_of_bedrooms %> bed<%= @apartment.number_of_bedrooms > 1 ? "s" : "" %></span>&nbsp&nbsp
      <span><i class="fa-solid fa-bath"></i><%= @apartment.number_of_bedrooms %> bath<%= @apartment.number_of_bedrooms > 1 ? "s" : "" %></span>&nbsp&nbsp
      <span><i class="fa-solid fa-house"></i>100 sqm</span>
    </h6>
  </div>
</div>

<div class="body-1">
  <div class="row main-text-show">
    <div class="col-8">
      <div class="container">
        <h3 class='my-2'>Description</h4>
        <p><%= @apartment.description %></p>
        <h3 class='mt-2 mb-1'>Furnished apartment</h4>
        <p>Vero earum commodi soluta.", "Quaerat fuga cumque et vero eveniet omnis ut.", "Cumque sit dolor ut est consequuntur.</p>
        <p>
          More details...
        </p>
        <h3 class='mt-2 mb-1'>Cozy environment</h4>
        <p>Your Tabas apartment already comes with modern and sophisticated furniture, a fully well equipped kitchen with first-class appliances, a coffee machine in capsules and utensils, such as: crockery, bowls, pans and cutlery. The decoration makes the environments even more pleasant and is also on us.</p>
        <h3 class='mt-2 mb-1'>Comfortable and relaxing</h4>
        <p>Rooms equipped with Smart TV, cable TV and Wi-Fi make the space ready to have fun, study or work from home. Be happy to find that every room at Tabas comes with high quality mattresses, luxury linens and towels. And those are just some of the amenities of this apartment. We take care of everything so you can simply enjoy your stay and feel at home.</p>
        <h3 class='mt-2 mb-1'>Good location</h4>
        <p>This Tabas apartment is located in Vila Buarque - São Paulo, close to key interest points of the region.</p>
        <h3 class='mt-2 mb-1'>Easy booking</h4>
        <p>Choose the length of your stay and rent directly from the website in a few minutes. All that, knowing exactly how much you will pay, with no hidden fees.</p>
      </div>
    </div>
    <div class="col-4">
      <div class="default-card-right-column-show">
        <h5>from <i class="fa-solid fa-brazilian-real-sign"></i><%= @apartment.price_per_month %>/mo</h5>
        <h5><small>Available</small> 13th Sep</h5>
        <div class="d-grid gap-2">
          <button class="btn btn-dark my-1 rounded-button-show" type="button"><strong>Rent now</strong></button>
          <button class="btn btn-outline-dark rounded-button-show" type="button"><i class="fa-brands fa-whatsapp"></i>&nbsp&nbsp<strong>WhatsApp us</strong></button>
        </div>
        <p href="#" class='text-center mt-3 contact-us'><a href="#"><small><u>or Contact us</u></small></a></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabas Clone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("favicon-120.png") %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="body-margin">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto max-w-7xl py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8" style='margin-bottom: 80px;'>
      <div class="space-y-8 xl:col-span-1">
        <h3 class="text-base font-medium text-gray-900">CONTACT US</h3>
        <p class="text-base text-gray-500"><i class="fa-solid fa-location-dot"></i> Av. Nove de Julho, 5109 2º floor, Itaim Bibi, São Paulo - SP, 01407-200</p>
        <div class="flex space-x-6">
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Instagram</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
            </svg>
          </a>

          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Facebook</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
      </div>
      <div class="mt-12 grid grid-cols-2 gap-8 xl:col-span-2 xl:mt-0">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-base font-medium text-gray-900">GENERAL INFO</h3>
            <ul role="list" class="mt-4 space-y-4 menu-footer">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">FAQ</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">About us</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">Careers</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">Contact us</a>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-base font-medium text-gray-900">FOR OWNERS</h3>
            <ul role="list" class="mt-4 space-y-4 menu-footer">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">proprietario@tabas.com.br</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">+55 11 4632 3312</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-base font-medium text-gray-900">FOR CORPORATE</h3>
            <ul role="list" class="mt-4 space-y-4 menu-footer">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">corporate@tabas.com.br</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">+55 11 4632 3312</a>
              </li>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-base font-medium text-gray-900">DOWNLOAD OUR APP</h3>
            <ul role="list" class="mt-4 space-y-4 menu-footer">
              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">Claim</a>
              </li>

              <li>
                <a href="#" class="text-base text-gray-500 hover:text-gray-900">Privacy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-12 pb-1 border-t border-gray-200 pt-8 row" style="height: 10px; margin-top: -20px;">
      <div class='col-4'>
        <p class="text-base xl:text-center">Copyright &copy; 2022 Tabas. All rights reserved</p>
      </div>
      <div class="col-4">
        <%= link_to root_path do %>
          <img class="block h-8 w-auto lg:hidden mx-auto" src="https://tabas.com/packs/media/images/logo-dark-e153277a7756ce181443a0227061abf3.svg" alt="Tabas">
          <img class="hidden h-8 w-auto lg:block mx-auto" src="https://tabas.com/packs/media/images/logo-dark-e153277a7756ce181443a0227061abf3.svg" alt="Tabas">
        <% end %>
      </div>
      <div class="col-4">
        <span class="isolate inline-flex rounded-md shadow-sm">
          <button type="button" class="relative inline-flex items-center rounded-l-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500">Cookies Policy</button>
          <button type="button" class="relative -ml-px inline-flex items-center border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500">Terms & Conditions</button>
          <button type="button" class="relative -ml-px inline-flex items-center rounded-r-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500">Privacy Policy</button>
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top config-navbar" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <img class="block h-8 w-auto lg:hidden" src="https://tabas.com/packs/media/images/logo-dark-e153277a7756ce181443a0227061abf3.svg" alt="Tabas">
      <img class="hidden h-8 w-auto lg:block" src="https://tabas.com/packs/media/images/logo-dark-e153277a7756ce181443a0227061abf3.svg" alt="Tabas">
    <% end %>

  <div>
  </div>

  <div class="ms-auto d-inline-flex">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="#"><i class="fa-solid fa-globe"></i></a></a>
        <a class="nav-item nav-link" href="#">SUPORT</a>
        <%= link_to "SIGN UP", new_member_registration_path, class: 'nav-item nav-link' %>
        <%= link_to "LOG IN", new_member_session_path, class: 'nav-item nav-link' %>
      </div>
    </div>
  </div>
  </div>
</nav>